Shares/Shares/models.py
from Shares import db

class Company(db.Model):
    __tablename__="company"

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.Text)
    price = db.Column(db.Integer)
    quantity = db.Column(db.Integer)
    total = db.Column(db.Integer)

    def __init__(self,name,price,quantity,total):
        self.name  = name
        self.price = price
        self.quantity = quantity
        self.total = total

    def __repr__(self):
        return f"name is {self.name} price is {self.price} quantity is {self.quantity} total is {self.total}"

Shares/Shares/ShareNames/forms.py
from flask_wtf import FlaskForm
from wtforms import IntegerField,StringField,SubmitField

class AddForm(FlaskForm):
    name = StringField("enter the name of that share")
    price = IntegerField("enter the price of that share")
    quantity = IntegerField("enter the quantity")
    submit = SubmitField("submit")


class DeleteForm(FlaskForm):
    id = IntegerField("enter the Id")
    submit = SubmitField("Delete")

Shares/Shares/ShareNames/views.py
from flask import Flask,Blueprint,render_template,redirect,url_for
from Shares import db
from Shares.ShareNames.forms import AddForm,DeleteForm
from Shares.models import Company

shares_blueprint = Blueprint('Shares',__name__,template_folder='templates/ShareNames')





@shares_blueprint.route('/add',methods=['GET','POST'])
def add():
    form = AddForm()
    if form.validate_on_submit():
        name = form.name.data
        price = form.price.data
        quantity = form.quantity.data
        Total = price * quantity

        sha = Company(name,price,quantity,Total)
        db.session.add(sha)
        db.session.commit()

        return redirect(url_for('Shares.list'))

    return render_template('add.html',form=form)

@shares_blueprint.route('/list')
def list():
    shar = Company.query.all()
    return render_template('list.html',shar=shar)

@shares_blueprint.route('/delete',methods=['GET','POST'])
def delete():
    form = DeleteForm()

    if form.validate_on_submit():
        id = form.id.data
        pup = Company.query.get(id)
        db.session.delete(pup)
        db.session.commit()

        return redirect(url_for('Shares.list'))
    return render_template('delete.html',form=form)

Shares/Shares/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)


app.config['SECRET_KEY'] = 'mysecretkey'
basedir = os.path.abspath(os.path.dirname(__file__))
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(basedir, 'data.sqlite')
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False



db = SQLAlchemy(app)
Migrate(app,db)




from Shares.ShareNames.views import shares_blueprint
app.register_blueprint(shares_blueprint,url_prefix="/ShareNames")

Shares/Shares/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <title>Shares</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Shares Database</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
         <div class="navbar-nav">
           <a class="nav-link active" href="{{url_for('index')}}">Home <span class="sr-only">(current)</span></a>
           <a class="nav-link" href="{{url_for('Shares.add')}}">add</a>
           <a class="nav-link" href="{{url_for('Shares.list')}}">list</a>
           <a class="nav-link" href="{{url_for('Shares.delete')}}">delete</a>
         </div>
       </div>
    </nav>
    {%block content%}
    {% endblock%}
  </body>
</html>

Shares/Shares/templates/home.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
  <h1> welcome to your shares data base </h1>
</div>
{% endblock %}